---
abstract: 'Manage services necessary for automated or interactive testing'
author:
  - 'Michael Alan Dorman <mdorman@ironicdesign.com>'
build_requires:
  File::Find: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-Service
requires:
  Class::Load: 0
  Dist::Zilla::App: 0
  File::Path: 0
  File::Slurp: 0
  File::Spec: 0
  File::Temp: 0
  IPC::Run: 0
  Log::Any: 0
  Module::Build: 0
  Moo: 0
  Moo::Role: 0
  Path::Class: 0
  Try::Tiny: 0
  base: 0
  strict: 0
  warnings: 0
version: 0.90
